// Bem-vindo ao modo de exibição de consulta DAX! Saiba mais sobre consultas DAX em https://aka.ms/dax-queries.
// Clique com o botão direito do mouse em tabelas, colunas ou medidas no painel de dados para acessar consultas rápidas ou peça ajuda ao Copilot para escrever DAX.

// Selecione "Executar" para experimentar esta consulta DAX de exemplo.
EVALUATE
{
    ( "1. Total geral",        [Faturamento Recebido Rateado] ),
    ( "2. Soma por consultor", SUMX( VALUES( dim_volunteers[nome] ), [Faturamento Recebido Rateado] ) ),
    ( "3. Receita Recebida",   [Receita Recebida] )
}


EVALUATE
CALCULATETABLE(
    SELECTCOLUMNS(
        fact_invoices,
        "Boleto",    fact_invoices[codigo_boleto],
        "Pagamento", fact_invoices[valor_pagamento],
        "Situacao",  fact_invoices[descricao_situacao_boleto],
        "Data",      fact_invoices[data_pagamento]
    ),
    fact_invoices[valor_pagamento] > 0,
    NOT fact_invoices[codigo_boleto] IN VALUES( bridge_invoices_vehicles[codigo_boleto] )
)
ORDER BY [Pagamento] DESC


