table dim_volunteers
	lineageTag: 6a0853db-d3de-4b60-8bda-693a7808aa80

	column codigo_voluntario
		dataType: string
		lineageTag: b9d4f492-b517-4831-a418-b19d974e5133
		summarizeBy: none
		sourceColumn: codigo_voluntario

		annotation SummarizationSetBy = Automatic

	column nome
		dataType: string
		lineageTag: f2d3740f-333d-42ed-bca8-674276e72440
		summarizeBy: none
		sourceColumn: nome

		annotation SummarizationSetBy = Automatic

	column cpf
		dataType: string
		lineageTag: 46041942-95aa-414c-8bed-e55ef449dd59
		summarizeBy: none
		sourceColumn: cpf

		annotation SummarizationSetBy = Automatic

	column cep
		dataType: string
		lineageTag: 9eaff62c-0500-4d4c-b336-ce893d21fadd
		summarizeBy: none
		sourceColumn: cep

		annotation SummarizationSetBy = Automatic

	column telefone
		dataType: string
		lineageTag: f32b7cc2-74fb-4c52-9e16-616f83f5a583
		summarizeBy: none
		sourceColumn: telefone

		annotation SummarizationSetBy = Automatic

	column telefone_comercial
		dataType: string
		lineageTag: a75b9bf7-a1c8-4059-9549-59963538791d
		summarizeBy: none
		sourceColumn: telefone_comercial

		annotation SummarizationSetBy = Automatic

	column celular
		dataType: string
		lineageTag: bb7647cd-d471-4c5a-b630-b8a6384ce416
		summarizeBy: none
		sourceColumn: celular

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: e20e804a-a984-425d-a722-0e24034016d2
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column situacao
		dataType: string
		lineageTag: 63fdd933-02c9-44cc-b14e-3cf720114d5f
		summarizeBy: none
		sourceColumn: situacao

		annotation SummarizationSetBy = Automatic

	column codigo_classificacao
		dataType: string
		isHidden
		lineageTag: 927c6a3d-5fce-48a3-b67c-dfddca92e700
		summarizeBy: none
		sourceColumn: codigo_classificacao

		annotation SummarizationSetBy = Automatic

	column logradouro
		dataType: string
		lineageTag: 75cc0f84-5c76-4264-a0fc-4e0874c88967
		summarizeBy: none
		sourceColumn: logradouro

		annotation SummarizationSetBy = Automatic

	column numero
		dataType: string
		lineageTag: 1a2117f4-de5f-4348-9190-dc7d9ad965d5
		summarizeBy: none
		sourceColumn: numero

		annotation SummarizationSetBy = Automatic

	column complemento
		dataType: string
		lineageTag: 988eb481-1ecc-44c4-90b0-8ac68d80f27f
		summarizeBy: none
		sourceColumn: complemento

		annotation SummarizationSetBy = Automatic

	column bairro
		dataType: string
		lineageTag: 274971ed-b96f-40c5-a488-9939d3d04885
		summarizeBy: none
		sourceColumn: bairro

		annotation SummarizationSetBy = Automatic

	column cidade
		dataType: string
		lineageTag: 36c4c82a-836a-43ef-ad01-c5f6e172984b
		summarizeBy: none
		sourceColumn: cidade

		annotation SummarizationSetBy = Automatic

	column estado
		dataType: string
		lineageTag: 14b321a9-ad34-4001-bb36-e0c28bc4e372
		summarizeBy: none
		sourceColumn: estado

		annotation SummarizationSetBy = Automatic

	column data_cadastro
		dataType: dateTime
		formatString: Long Date
		lineageTag: bfbabef1-504b-4b74-8120-fb18776db0b2
		summarizeBy: none
		sourceColumn: data_cadastro

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_nascimento
		dataType: dateTime
		formatString: Long Date
		lineageTag: 93717ec4-d8d5-4baa-9033-3c82e25d34ff
		summarizeBy: none
		sourceColumn: data_nascimento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column cooperativas
		dataType: string
		lineageTag: a0991716-4a4d-4681-9432-d74b8d42de75
		summarizeBy: none
		sourceColumn: cooperativas

		annotation SummarizationSetBy = Automatic

	column situacao_origem
		dataType: string
		lineageTag: 24b5de19-be1b-47e0-88f7-b4396a24f21c
		summarizeBy: none
		sourceColumn: situacao_origem

		annotation SummarizationSetBy = Automatic

	column criado_em
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: b4236edb-8445-4460-b6be-f273fd36ef72
		summarizeBy: none
		sourceColumn: criado_em

		annotation SummarizationSetBy = Automatic

	column atualizado_em
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 99eaf75d-b85a-4d78-a248-a585ee455bd7
		summarizeBy: none
		sourceColumn: atualizado_em

		annotation SummarizationSetBy = Automatic

	column data_referencia
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7bc20e79-903f-4cc2-b888-d4ff87dde948
		summarizeBy: none
		sourceColumn: data_referencia

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_volunteers = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("localhost", "sga_dw"),
				    public_dim_volunteers = Fonte{[Schema="public",Item="dim_volunteers"]}[Data],
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(public_dim_volunteers,{{"nome", Text.Proper, type text}})
				in
				    #"Colocar Cada Palavra Em Maiúscula"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

